"""Loan product seed data — extracted from server.py.

Replace by an admin import endpoint later. Currently loaded on startup.
"""

LOAN_PRODUCTS = [
    # Personal Loans
    {"product_id": "sbi_personal", "bank_name": "SBI", "product_name": "SBI Personal Loan", "loan_type": "personal", "interest_rate": 11.0, "processing_fee_pct": 1.5, "max_amount": 2000000, "min_amount": 25000, "max_tenure_months": 72, "min_tenure_months": 6, "foreclosure_charge_pct": 3.0, "min_income": 15000, "min_credit_score": 650, "features": ["No collateral required", "Quick disbursement"], "is_active": True},
    {"product_id": "hdfc_personal", "bank_name": "HDFC Bank", "product_name": "HDFC Personal Loan", "loan_type": "personal", "interest_rate": 10.5, "processing_fee_pct": 2.0, "max_amount": 4000000, "min_amount": 50000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 4.0, "min_income": 25000, "min_credit_score": 700, "features": ["Instant approval", "Flexible tenure"], "is_active": True},
    {"product_id": "icici_personal", "bank_name": "ICICI Bank", "product_name": "ICICI Personal Loan", "loan_type": "personal", "interest_rate": 10.75, "processing_fee_pct": 2.5, "max_amount": 5000000, "min_amount": 50000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 5.0, "min_income": 25000, "min_credit_score": 700, "features": ["Pre-approved offers", "Doorstep service"], "is_active": True},
    {"product_id": "bajaj_personal", "bank_name": "Bajaj Finserv", "product_name": "Bajaj Personal Loan", "loan_type": "personal", "interest_rate": 12.0, "processing_fee_pct": 2.0, "max_amount": 2500000, "min_amount": 25000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 3.5, "min_income": 15000, "min_credit_score": 625, "features": ["Flexi loan option", "Part-prepayment"], "is_active": True},
    {"product_id": "kotak_personal", "bank_name": "Kotak Mahindra", "product_name": "Kotak Personal Loan", "loan_type": "personal", "interest_rate": 10.99, "processing_fee_pct": 2.5, "max_amount": 4000000, "min_amount": 50000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 4.0, "min_income": 20000, "min_credit_score": 680, "features": ["Digital process", "Balance transfer"], "is_active": True},
    # Home Loans
    {"product_id": "sbi_home", "bank_name": "SBI", "product_name": "SBI Home Loan", "loan_type": "home", "interest_rate": 8.5, "processing_fee_pct": 0.35, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 360, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 25000, "min_credit_score": 650, "features": ["No foreclosure charges", "Tax benefits up to 3.5L"], "is_active": True},
    {"product_id": "hdfc_home", "bank_name": "HDFC Bank", "product_name": "HDFC Home Loan", "loan_type": "home", "interest_rate": 8.75, "processing_fee_pct": 0.50, "max_amount": 100000000, "min_amount": 500000, "max_tenure_months": 360, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 25000, "min_credit_score": 650, "features": ["Doorstep service", "Balance transfer facility"], "is_active": True},
    {"product_id": "lic_home", "bank_name": "LIC Housing", "product_name": "LIC Home Loan", "loan_type": "home", "interest_rate": 8.35, "processing_fee_pct": 0.25, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 360, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 20000, "min_credit_score": 625, "features": ["Lowest processing fee", "Long tenure"], "is_active": True},
    {"product_id": "icici_home", "bank_name": "ICICI Bank", "product_name": "ICICI Home Loan", "loan_type": "home", "interest_rate": 8.60, "processing_fee_pct": 0.50, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 360, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 25000, "min_credit_score": 675, "features": ["Fast processing", "Online tracking"], "is_active": True},
    {"product_id": "axis_home", "bank_name": "Axis Bank", "product_name": "Axis Home Loan", "loan_type": "home", "interest_rate": 8.70, "processing_fee_pct": 1.0, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 360, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 25000, "min_credit_score": 675, "features": ["Women borrower discount", "NRI home loans"], "is_active": True},
    # Car Loans
    {"product_id": "sbi_car", "bank_name": "SBI", "product_name": "SBI Car Loan", "loan_type": "car", "interest_rate": 8.65, "processing_fee_pct": 0.5, "max_amount": 5000000, "min_amount": 100000, "max_tenure_months": 84, "min_tenure_months": 12, "foreclosure_charge_pct": 2.0, "min_income": 20000, "min_credit_score": 650, "features": ["Low interest rate", "100% on-road financing"], "is_active": True},
    {"product_id": "hdfc_car", "bank_name": "HDFC Bank", "product_name": "HDFC Car Loan", "loan_type": "car", "interest_rate": 8.80, "processing_fee_pct": 0.5, "max_amount": 5000000, "min_amount": 100000, "max_tenure_months": 84, "min_tenure_months": 12, "foreclosure_charge_pct": 3.0, "min_income": 20000, "min_credit_score": 675, "features": ["Quick disbursement", "Flexible EMI"], "is_active": True},
    {"product_id": "icici_car", "bank_name": "ICICI Bank", "product_name": "ICICI Car Loan", "loan_type": "car", "interest_rate": 8.75, "processing_fee_pct": 0.5, "max_amount": 5000000, "min_amount": 100000, "max_tenure_months": 84, "min_tenure_months": 12, "foreclosure_charge_pct": 5.0, "min_income": 20000, "min_credit_score": 650, "features": ["Used car loans", "Dealer partnerships"], "is_active": True},
    # Education Loans
    {"product_id": "sbi_edu", "bank_name": "SBI", "product_name": "SBI Education Loan", "loan_type": "education", "interest_rate": 8.15, "processing_fee_pct": 0, "max_amount": 15000000, "min_amount": 100000, "max_tenure_months": 180, "min_tenure_months": 36, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["No processing fee", "Moratorium period", "Tax benefit 80E"], "is_active": True},
    {"product_id": "hdfc_edu", "bank_name": "HDFC Credila", "product_name": "HDFC Education Loan", "loan_type": "education", "interest_rate": 9.0, "processing_fee_pct": 1.0, "max_amount": 20000000, "min_amount": 100000, "max_tenure_months": 180, "min_tenure_months": 36, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Study abroad loans", "Co-applicant income"], "is_active": True},
    {"product_id": "axis_edu", "bank_name": "Axis Bank", "product_name": "Axis Education Loan", "loan_type": "education", "interest_rate": 9.70, "processing_fee_pct": 1.0, "max_amount": 7500000, "min_amount": 50000, "max_tenure_months": 180, "min_tenure_months": 36, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Quick approval", "Living expenses covered"], "is_active": True},
    # Bike Loans
    {"product_id": "hdfc_bike", "bank_name": "HDFC Bank", "product_name": "HDFC Bike Loan", "loan_type": "bike", "interest_rate": 9.5, "processing_fee_pct": 1.0, "max_amount": 500000, "min_amount": 25000, "max_tenure_months": 48, "min_tenure_months": 6, "foreclosure_charge_pct": 5.0, "min_income": 12000, "min_credit_score": 600, "features": ["Minimal docs", "Instant approval"], "is_active": True},
    {"product_id": "bajaj_bike", "bank_name": "Bajaj Finserv", "product_name": "Bajaj Bike Loan", "loan_type": "bike", "interest_rate": 10.0, "processing_fee_pct": 1.5, "max_amount": 400000, "min_amount": 15000, "max_tenure_months": 48, "min_tenure_months": 6, "foreclosure_charge_pct": 4.0, "min_income": 10000, "min_credit_score": 600, "features": ["Low down payment", "Wide network"], "is_active": True},
    {"product_id": "mahindra_bike", "bank_name": "Mahindra Finance", "product_name": "Mahindra Bike Loan", "loan_type": "bike", "interest_rate": 11.0, "processing_fee_pct": 1.0, "max_amount": 300000, "min_amount": 15000, "max_tenure_months": 48, "min_tenure_months": 6, "foreclosure_charge_pct": 5.0, "min_income": 8000, "min_credit_score": 550, "features": ["Rural-friendly", "Flexible repayment"], "is_active": True},
    # Additional Personal Loans
    {"product_id": "pnb_personal", "bank_name": "PNB", "product_name": "PNB Personal Loan", "loan_type": "personal", "interest_rate": 10.85, "processing_fee_pct": 1.0, "max_amount": 1000000, "min_amount": 25000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 3.0, "min_income": 15000, "min_credit_score": 650, "features": ["Government bank trust", "Low processing fee"], "is_active": True},
    {"product_id": "bob_personal", "bank_name": "Bank of Baroda", "product_name": "Baroda Personal Loan", "loan_type": "personal", "interest_rate": 11.25, "processing_fee_pct": 1.0, "max_amount": 1500000, "min_amount": 25000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 3.0, "min_income": 15000, "min_credit_score": 650, "features": ["No hidden charges", "Online tracking"], "is_active": True},
    {"product_id": "indusind_personal", "bank_name": "IndusInd Bank", "product_name": "IndusInd Personal Loan", "loan_type": "personal", "interest_rate": 10.49, "processing_fee_pct": 2.5, "max_amount": 5000000, "min_amount": 50000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 4.0, "min_income": 25000, "min_credit_score": 700, "features": ["Attractive rates", "Minimal docs"], "is_active": True},
    {"product_id": "tata_personal", "bank_name": "Tata Capital", "product_name": "Tata Capital Personal Loan", "loan_type": "personal", "interest_rate": 10.99, "processing_fee_pct": 2.0, "max_amount": 3500000, "min_amount": 75000, "max_tenure_months": 72, "min_tenure_months": 12, "foreclosure_charge_pct": 4.0, "min_income": 20000, "min_credit_score": 675, "features": ["Tata group trust", "Quick disbursal"], "is_active": True},
    {"product_id": "idfc_personal", "bank_name": "IDFC First", "product_name": "IDFC First Personal Loan", "loan_type": "personal", "interest_rate": 10.49, "processing_fee_pct": 2.0, "max_amount": 4000000, "min_amount": 20000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 4.0, "min_income": 20000, "min_credit_score": 700, "features": ["Zero foreclosure", "Digital journey"], "is_active": True},
    {"product_id": "yes_personal", "bank_name": "Yes Bank", "product_name": "Yes Bank Personal Loan", "loan_type": "personal", "interest_rate": 11.5, "processing_fee_pct": 2.0, "max_amount": 4000000, "min_amount": 50000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 3.0, "min_income": 20000, "min_credit_score": 680, "features": ["Instant e-approval", "Salary credit not needed"], "is_active": True},
    {"product_id": "axis_personal", "bank_name": "Axis Bank", "product_name": "Axis Personal Loan", "loan_type": "personal", "interest_rate": 10.75, "processing_fee_pct": 2.0, "max_amount": 5000000, "min_amount": 50000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 4.0, "min_income": 25000, "min_credit_score": 700, "features": ["Pre-approved for salary a/c", "Step-up EMI"], "is_active": True},
    {"product_id": "canara_personal", "bank_name": "Canara Bank", "product_name": "Canara Personal Loan", "loan_type": "personal", "interest_rate": 11.15, "processing_fee_pct": 0.5, "max_amount": 1000000, "min_amount": 25000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 2.0, "min_income": 15000, "min_credit_score": 650, "features": ["Lowest processing fee", "Govt bank reliability"], "is_active": True},
    # Additional Home Loans
    {"product_id": "pnb_home", "bank_name": "PNB", "product_name": "PNB Home Loan", "loan_type": "home", "interest_rate": 8.40, "processing_fee_pct": 0.35, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 360, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 20000, "min_credit_score": 650, "features": ["Govt bank low rate", "No foreclosure charges"], "is_active": True},
    {"product_id": "bob_home", "bank_name": "Bank of Baroda", "product_name": "Baroda Home Loan", "loan_type": "home", "interest_rate": 8.45, "processing_fee_pct": 0.25, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 360, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 20000, "min_credit_score": 650, "features": ["Lowest fees", "Step-up repayment"], "is_active": True},
    {"product_id": "canara_home", "bank_name": "Canara Bank", "product_name": "Canara Home Loan", "loan_type": "home", "interest_rate": 8.40, "processing_fee_pct": 0.50, "max_amount": 30000000, "min_amount": 300000, "max_tenure_months": 360, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 18000, "min_credit_score": 625, "features": ["Low income threshold", "Rural housing available"], "is_active": True},
    {"product_id": "federal_home", "bank_name": "Federal Bank", "product_name": "Federal Home Loan", "loan_type": "home", "interest_rate": 8.65, "processing_fee_pct": 0.50, "max_amount": 30000000, "min_amount": 500000, "max_tenure_months": 360, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 20000, "min_credit_score": 650, "features": ["Kerala focus", "NRI home loans"], "is_active": True},
    {"product_id": "union_home", "bank_name": "Union Bank", "product_name": "Union Home Loan", "loan_type": "home", "interest_rate": 8.35, "processing_fee_pct": 0.25, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 360, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 18000, "min_credit_score": 625, "features": ["One of lowest rates", "Wide branch network"], "is_active": True},
    # Additional Car Loans
    {"product_id": "tata_car", "bank_name": "Tata Capital", "product_name": "Tata Capital Car Loan", "loan_type": "car", "interest_rate": 8.50, "processing_fee_pct": 0.5, "max_amount": 5000000, "min_amount": 100000, "max_tenure_months": 84, "min_tenure_months": 12, "foreclosure_charge_pct": 2.5, "min_income": 18000, "min_credit_score": 650, "features": ["Tata group assurance", "Used car finance"], "is_active": True},
    {"product_id": "axis_car", "bank_name": "Axis Bank", "product_name": "Axis Car Loan", "loan_type": "car", "interest_rate": 8.70, "processing_fee_pct": 0.5, "max_amount": 5000000, "min_amount": 100000, "max_tenure_months": 84, "min_tenure_months": 12, "foreclosure_charge_pct": 3.0, "min_income": 20000, "min_credit_score": 675, "features": ["Instant approval", "EV car loans"], "is_active": True},
    {"product_id": "pnb_car", "bank_name": "PNB", "product_name": "PNB Car Loan", "loan_type": "car", "interest_rate": 8.55, "processing_fee_pct": 0.35, "max_amount": 3000000, "min_amount": 100000, "max_tenure_months": 84, "min_tenure_months": 12, "foreclosure_charge_pct": 2.0, "min_income": 18000, "min_credit_score": 650, "features": ["Low processing fee", "Govt bank trust"], "is_active": True},
    # Gold Loans
    {"product_id": "sbi_gold", "bank_name": "SBI", "product_name": "SBI Gold Loan", "loan_type": "gold", "interest_rate": 7.5, "processing_fee_pct": 0.5, "max_amount": 5000000, "min_amount": 20000, "max_tenure_months": 36, "min_tenure_months": 3, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["No income proof needed", "Quick disbursal in 30 mins"], "is_active": True},
    {"product_id": "hdfc_gold", "bank_name": "HDFC Bank", "product_name": "HDFC Gold Loan", "loan_type": "gold", "interest_rate": 8.0, "processing_fee_pct": 1.0, "max_amount": 5000000, "min_amount": 25000, "max_tenure_months": 24, "min_tenure_months": 3, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Instant valuation", "Doorstep service", "No foreclosure"], "is_active": True},
    {"product_id": "muthoot_gold", "bank_name": "Muthoot Finance", "product_name": "Muthoot Gold Loan", "loan_type": "gold", "interest_rate": 9.0, "processing_fee_pct": 0, "max_amount": 10000000, "min_amount": 1500, "max_tenure_months": 12, "min_tenure_months": 3, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Zero processing fee", "Pan-India branches", "Instant cash"], "is_active": True},
    {"product_id": "manappuram_gold", "bank_name": "Manappuram Finance", "product_name": "Manappuram Gold Loan", "loan_type": "gold", "interest_rate": 9.9, "processing_fee_pct": 0, "max_amount": 5000000, "min_amount": 1500, "max_tenure_months": 12, "min_tenure_months": 1, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Online gold loan", "Lowest min amount", "Flexible repayment"], "is_active": True},
    {"product_id": "canara_gold", "bank_name": "Canara Bank", "product_name": "Canara Gold Loan", "loan_type": "gold", "interest_rate": 7.35, "processing_fee_pct": 0.25, "max_amount": 3500000, "min_amount": 10000, "max_tenure_months": 36, "min_tenure_months": 3, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["One of lowest rates", "Govt bank safety", "No income docs"], "is_active": True},
    # Used Vehicle / 2nd Hand Purchase Loans
    {"product_id": "hdfc_used_car", "bank_name": "HDFC Bank", "product_name": "HDFC Used Car Loan", "loan_type": "used_vehicle", "interest_rate": 11.5, "processing_fee_pct": 1.5, "max_amount": 2500000, "min_amount": 100000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 5.0, "min_income": 18000, "min_credit_score": 650, "features": ["Up to 7 yr old vehicles", "Dealer tie-ups"], "is_active": True},
    {"product_id": "icici_used_car", "bank_name": "ICICI Bank", "product_name": "ICICI Used Car Loan", "loan_type": "used_vehicle", "interest_rate": 11.0, "processing_fee_pct": 1.5, "max_amount": 3000000, "min_amount": 100000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 5.0, "min_income": 18000, "min_credit_score": 650, "features": ["Cars up to 10 yrs old", "Doorstep inspection"], "is_active": True},
    {"product_id": "axis_used_car", "bank_name": "Axis Bank", "product_name": "Axis Used Car Loan", "loan_type": "used_vehicle", "interest_rate": 11.75, "processing_fee_pct": 1.0, "max_amount": 2500000, "min_amount": 100000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 4.0, "min_income": 20000, "min_credit_score": 675, "features": ["Certified pre-owned", "Quick valuation"], "is_active": True},
    {"product_id": "tata_used_car", "bank_name": "Tata Capital", "product_name": "Tata Capital Used Vehicle Loan", "loan_type": "used_vehicle", "interest_rate": 12.0, "processing_fee_pct": 1.5, "max_amount": 2000000, "min_amount": 50000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 3.0, "min_income": 15000, "min_credit_score": 625, "features": ["Used 2-wheelers too", "Pan-India service"], "is_active": True},
    # Plot / Land Purchase Loans
    {"product_id": "sbi_plot", "bank_name": "SBI", "product_name": "SBI Plot Loan", "loan_type": "plot", "interest_rate": 8.7, "processing_fee_pct": 0.35, "max_amount": 30000000, "min_amount": 500000, "max_tenure_months": 180, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 25000, "min_credit_score": 650, "features": ["No foreclosure charges", "Tax benefits", "Realty Plus scheme"], "is_active": True},
    {"product_id": "hdfc_plot", "bank_name": "HDFC Bank", "product_name": "HDFC Plot Loan", "loan_type": "plot", "interest_rate": 9.0, "processing_fee_pct": 0.50, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 180, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 30000, "min_credit_score": 700, "features": ["Construction linked plans", "Balance transfer"], "is_active": True},
    {"product_id": "pnb_plot", "bank_name": "PNB", "product_name": "PNB Plot Loan", "loan_type": "plot", "interest_rate": 8.55, "processing_fee_pct": 0.25, "max_amount": 20000000, "min_amount": 300000, "max_tenure_months": 180, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 20000, "min_credit_score": 650, "features": ["Lowest govt bank rate", "Rural plots eligible"], "is_active": True},
    {"product_id": "bob_plot", "bank_name": "Bank of Baroda", "product_name": "Baroda Plot Loan", "loan_type": "plot", "interest_rate": 8.65, "processing_fee_pct": 0.25, "max_amount": 20000000, "min_amount": 300000, "max_tenure_months": 180, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 18000, "min_credit_score": 625, "features": ["Low processing fee", "Construction top-up available"], "is_active": True},
    # Loan Against Mutual Funds
    {"product_id": "hdfc_mf_loan", "bank_name": "HDFC Bank", "product_name": "HDFC Loan Against Mutual Funds", "loan_type": "mutual_funds", "interest_rate": 9.5, "processing_fee_pct": 0.5, "max_amount": 10000000, "min_amount": 50000, "max_tenure_months": 36, "min_tenure_months": 6, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Continue earning MF returns", "No income proof", "Overdraft facility"], "is_active": True},
    {"product_id": "icici_mf_loan", "bank_name": "ICICI Bank", "product_name": "ICICI Loan Against Mutual Funds", "loan_type": "mutual_funds", "interest_rate": 9.0, "processing_fee_pct": 0.5, "max_amount": 10000000, "min_amount": 25000, "max_tenure_months": 36, "min_tenure_months": 6, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Digital pledge process", "Retain fund ownership", "No prepayment penalty"], "is_active": True},
    {"product_id": "kotak_mf_loan", "bank_name": "Kotak Mahindra", "product_name": "Kotak Loan Against Mutual Funds", "loan_type": "mutual_funds", "interest_rate": 9.25, "processing_fee_pct": 0, "max_amount": 5000000, "min_amount": 50000, "max_tenure_months": 36, "min_tenure_months": 6, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Zero processing fee", "Online process", "Quick disbursement"], "is_active": True},
    {"product_id": "axis_mf_loan", "bank_name": "Axis Bank", "product_name": "Axis Loan Against Mutual Funds", "loan_type": "mutual_funds", "interest_rate": 9.75, "processing_fee_pct": 0.5, "max_amount": 5000000, "min_amount": 25000, "max_tenure_months": 36, "min_tenure_months": 6, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Instant online pledge", "Overdraft & term loan options"], "is_active": True},
    # Refinance / Balance Transfer Loans
    {"product_id": "sbi_refinance", "bank_name": "SBI", "product_name": "SBI Balance Transfer", "loan_type": "refinance", "interest_rate": 8.5, "processing_fee_pct": 0.5, "max_amount": 50000000, "min_amount": 200000, "max_tenure_months": 360, "min_tenure_months": 12, "foreclosure_charge_pct": 0, "min_income": 20000, "min_credit_score": 650, "features": ["Lower your existing rate", "Zero foreclosure", "Top-up available"], "is_active": True},
    {"product_id": "hdfc_refinance", "bank_name": "HDFC Bank", "product_name": "HDFC Balance Transfer", "loan_type": "refinance", "interest_rate": 8.75, "processing_fee_pct": 0.5, "max_amount": 50000000, "min_amount": 200000, "max_tenure_months": 360, "min_tenure_months": 12, "foreclosure_charge_pct": 0, "min_income": 25000, "min_credit_score": 675, "features": ["Switch in 7 days", "No hidden charges", "Online tracking"], "is_active": True},
    {"product_id": "icici_refinance", "bank_name": "ICICI Bank", "product_name": "ICICI Balance Transfer", "loan_type": "refinance", "interest_rate": 8.65, "processing_fee_pct": 0.5, "max_amount": 50000000, "min_amount": 200000, "max_tenure_months": 360, "min_tenure_months": 12, "foreclosure_charge_pct": 0, "min_income": 25000, "min_credit_score": 675, "features": ["Quick processing", "Rate match guarantee", "Doorstep service"], "is_active": True},
    {"product_id": "axis_refinance", "bank_name": "Axis Bank", "product_name": "Axis Balance Transfer", "loan_type": "refinance", "interest_rate": 8.70, "processing_fee_pct": 1.0, "max_amount": 50000000, "min_amount": 200000, "max_tenure_months": 360, "min_tenure_months": 12, "foreclosure_charge_pct": 0, "min_income": 25000, "min_credit_score": 675, "features": ["Easy switch process", "Top-up option", "EMI reduction"], "is_active": True},
    # Business Term Loans
    {"product_id": "sbi_business", "bank_name": "SBI", "product_name": "SBI SME Business Loan", "loan_type": "business", "interest_rate": 10.0, "processing_fee_pct": 1.0, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 84, "min_tenure_months": 12, "foreclosure_charge_pct": 2.0, "min_income": 30000, "min_credit_score": 650, "features": ["Govt scheme benefits", "Collateral-free up to 1Cr", "Stand-Up India eligible"], "is_active": True, "corporate_tieups": ["psu", "SAIL", "govt"], "available_regions": ["pan_india"]},
    {"product_id": "hdfc_business", "bank_name": "HDFC Bank", "product_name": "HDFC Business Growth Loan", "loan_type": "business", "interest_rate": 11.5, "processing_fee_pct": 2.0, "max_amount": 75000000, "min_amount": 500000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 4.0, "min_income": 40000, "min_credit_score": 700, "features": ["Instant pre-approved", "Online application", "Flexible repayment"], "is_active": True, "corporate_tieups": ["gcc", "private"], "available_regions": ["pan_india"]},
    {"product_id": "icici_business", "bank_name": "ICICI Bank", "product_name": "ICICI InstaBIZ Business Loan", "loan_type": "business", "interest_rate": 11.0, "processing_fee_pct": 2.0, "max_amount": 50000000, "min_amount": 300000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 4.0, "min_income": 35000, "min_credit_score": 700, "features": ["Digital process", "Same-day disbursement", "No branch visit"], "is_active": True, "corporate_tieups": ["gcc", "private"], "available_regions": ["pan_india"]},
    {"product_id": "axis_business", "bank_name": "Axis Bank", "product_name": "Axis Business Term Loan", "loan_type": "business", "interest_rate": 11.25, "processing_fee_pct": 1.5, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 3.0, "min_income": 35000, "min_credit_score": 680, "features": ["End-use flexibility", "No collateral up to 75L", "Quick turnaround"], "is_active": True, "corporate_tieups": [], "available_regions": ["pan_india"]},
    {"product_id": "bob_business", "bank_name": "Bank of Baroda", "product_name": "Baroda MSME Loan", "loan_type": "business", "interest_rate": 9.75, "processing_fee_pct": 0.5, "max_amount": 25000000, "min_amount": 200000, "max_tenure_months": 84, "min_tenure_months": 12, "foreclosure_charge_pct": 0, "min_income": 20000, "min_credit_score": 625, "features": ["Mudra scheme eligible", "Low processing fee", "Govt subsidy available"], "is_active": True, "corporate_tieups": ["psu", "SAIL", "govt"], "available_regions": ["pan_india"]},
    # MSME / Mudra Loans
    {"product_id": "sbi_mudra", "bank_name": "SBI", "product_name": "SBI Mudra Loan (Shishu/Kishore/Tarun)", "loan_type": "msme", "interest_rate": 8.5, "processing_fee_pct": 0, "max_amount": 1000000, "min_amount": 10000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Zero processing fee", "No collateral", "Shishu: up to 50K, Kishore: up to 5L, Tarun: up to 10L"], "is_active": True, "corporate_tieups": [], "available_regions": ["pan_india"]},
    {"product_id": "pnb_mudra", "bank_name": "PNB", "product_name": "PNB Mudra Loan", "loan_type": "msme", "interest_rate": 9.0, "processing_fee_pct": 0, "max_amount": 1000000, "min_amount": 10000, "max_tenure_months": 60, "min_tenure_months": 12, "foreclosure_charge_pct": 0, "min_income": 0, "min_credit_score": 0, "features": ["Zero processing fee", "Govt backed scheme", "Quick approval"], "is_active": True, "corporate_tieups": ["psu", "govt"], "available_regions": ["pan_india"]},
    {"product_id": "canara_msme", "bank_name": "Canara Bank", "product_name": "Canara MSME Loan", "loan_type": "msme", "interest_rate": 9.5, "processing_fee_pct": 0.25, "max_amount": 5000000, "min_amount": 100000, "max_tenure_months": 84, "min_tenure_months": 12, "foreclosure_charge_pct": 0, "min_income": 15000, "min_credit_score": 600, "features": ["CGTMSE coverage", "Low interest for women", "Priority sector benefits"], "is_active": True, "corporate_tieups": ["psu"], "available_regions": ["pan_india"]},
    {"product_id": "sidbi_msme", "bank_name": "SIDBI", "product_name": "SIDBI MSME Assistance", "loan_type": "msme", "interest_rate": 9.25, "processing_fee_pct": 0.5, "max_amount": 25000000, "min_amount": 500000, "max_tenure_months": 84, "min_tenure_months": 24, "foreclosure_charge_pct": 0, "min_income": 25000, "min_credit_score": 650, "features": ["Direct MSME lender", "Technology upgrade loans", "Cluster development"], "is_active": True, "corporate_tieups": ["psu", "SAIL"], "available_regions": ["pan_india"]},
    # Working Capital Loans
    {"product_id": "sbi_wc", "bank_name": "SBI", "product_name": "SBI Working Capital Loan", "loan_type": "working_capital", "interest_rate": 9.5, "processing_fee_pct": 0.5, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 12, "min_tenure_months": 3, "foreclosure_charge_pct": 0, "min_income": 30000, "min_credit_score": 650, "features": ["Cash credit facility", "Overdraft available", "Revolving credit line"], "is_active": True, "corporate_tieups": ["psu", "SAIL", "govt"], "available_regions": ["pan_india"]},
    {"product_id": "hdfc_wc", "bank_name": "HDFC Bank", "product_name": "HDFC Working Capital", "loan_type": "working_capital", "interest_rate": 10.5, "processing_fee_pct": 1.0, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 12, "min_tenure_months": 3, "foreclosure_charge_pct": 0, "min_income": 40000, "min_credit_score": 700, "features": ["Digital monitoring", "Flexible limits", "Quick renewal"], "is_active": True, "corporate_tieups": ["gcc", "private"], "available_regions": ["pan_india"]},
    {"product_id": "icici_wc", "bank_name": "ICICI Bank", "product_name": "ICICI Working Capital Finance", "loan_type": "working_capital", "interest_rate": 10.25, "processing_fee_pct": 1.0, "max_amount": 50000000, "min_amount": 300000, "max_tenure_months": 12, "min_tenure_months": 3, "foreclosure_charge_pct": 0, "min_income": 35000, "min_credit_score": 680, "features": ["Online facility management", "Trade finance combo", "Supply chain finance"], "is_active": True, "corporate_tieups": ["gcc"], "available_regions": ["pan_india"]},
    # Loan Against Property (LAP) for Business
    {"product_id": "sbi_lap", "bank_name": "SBI", "product_name": "SBI Loan Against Property", "loan_type": "lap", "interest_rate": 8.75, "processing_fee_pct": 0.5, "max_amount": 75000000, "min_amount": 500000, "max_tenure_months": 180, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 25000, "min_credit_score": 650, "features": ["Lowest LAP rates", "Long tenure", "No end-use restriction"], "is_active": True, "corporate_tieups": ["psu", "SAIL", "govt"], "available_regions": ["pan_india"]},
    {"product_id": "hdfc_lap", "bank_name": "HDFC Bank", "product_name": "HDFC Loan Against Property", "loan_type": "lap", "interest_rate": 9.5, "processing_fee_pct": 1.0, "max_amount": 100000000, "min_amount": 500000, "max_tenure_months": 180, "min_tenure_months": 60, "foreclosure_charge_pct": 2.0, "min_income": 30000, "min_credit_score": 700, "features": ["High LTV ratio", "Balance transfer option", "Doorstep service"], "is_active": True, "corporate_tieups": ["gcc", "private"], "available_regions": ["pan_india"]},
    {"product_id": "axis_lap", "bank_name": "Axis Bank", "product_name": "Axis Loan Against Property", "loan_type": "lap", "interest_rate": 9.75, "processing_fee_pct": 1.0, "max_amount": 50000000, "min_amount": 500000, "max_tenure_months": 180, "min_tenure_months": 60, "foreclosure_charge_pct": 2.0, "min_income": 30000, "min_credit_score": 680, "features": ["Commercial & residential property", "Top-up facility", "Online tracking"], "is_active": True, "corporate_tieups": [], "available_regions": ["pan_india"]},
    {"product_id": "pnb_lap", "bank_name": "PNB", "product_name": "PNB Loan Against Property", "loan_type": "lap", "interest_rate": 8.85, "processing_fee_pct": 0.5, "max_amount": 50000000, "min_amount": 300000, "max_tenure_months": 180, "min_tenure_months": 60, "foreclosure_charge_pct": 0, "min_income": 20000, "min_credit_score": 625, "features": ["No foreclosure on floating", "Govt bank trust", "Low processing fee"], "is_active": True, "corporate_tieups": ["psu", "SAIL", "govt"], "available_regions": ["pan_india"]},
]

# Corporate tie-up and region metadata to patch onto existing products
PRODUCT_METADATA = {
    "sbi_personal": {"corporate_tieups": ["psu", "SAIL", "govt", "defence"], "available_regions": ["pan_india"]},
    "hdfc_personal": {"corporate_tieups": ["gcc", "private", "TCS", "Infosys", "Wipro"], "available_regions": ["pan_india"]},
    "icici_personal": {"corporate_tieups": ["gcc", "private", "Cognizant", "HCL"], "available_regions": ["pan_india"]},
    "bajaj_personal": {"corporate_tieups": ["private"], "available_regions": ["pan_india"]},
    "kotak_personal": {"corporate_tieups": ["gcc", "private"], "available_regions": ["Maharashtra", "Karnataka", "Delhi", "Tamil Nadu", "Telangana", "Gujarat"]},
    "axis_personal": {"corporate_tieups": ["gcc", "private"], "available_regions": ["pan_india"]},
    "indusind_personal": {"corporate_tieups": ["private"], "available_regions": ["Maharashtra", "Delhi", "Karnataka", "Tamil Nadu", "Telangana", "Gujarat", "West Bengal"]},
    "idfc_personal": {"corporate_tieups": [], "available_regions": ["Maharashtra", "Delhi", "Karnataka", "Tamil Nadu", "Telangana", "Gujarat", "Rajasthan"]},
    "yes_personal": {"corporate_tieups": ["private"], "available_regions": ["pan_india"]},
    "pnb_personal": {"corporate_tieups": ["psu", "SAIL", "govt", "defence"], "available_regions": ["pan_india"]},
    "bob_personal": {"corporate_tieups": ["psu", "SAIL", "govt"], "available_regions": ["pan_india"]},
    "tata_personal": {"corporate_tieups": ["private", "Tata Group"], "available_regions": ["pan_india"]},
    "canara_personal": {"corporate_tieups": ["psu", "govt"], "available_regions": ["pan_india"]},
    "sbi_home": {"corporate_tieups": ["psu", "SAIL", "govt", "defence"], "available_regions": ["pan_india"]},
    "hdfc_home": {"corporate_tieups": ["gcc", "private", "TCS", "Infosys"], "available_regions": ["pan_india"]},
    "icici_home": {"corporate_tieups": ["gcc", "private"], "available_regions": ["pan_india"]},
    "axis_home": {"corporate_tieups": ["gcc", "private"], "available_regions": ["pan_india"]},
    "lic_home": {"corporate_tieups": ["psu", "govt", "LIC agents"], "available_regions": ["pan_india"]},
    "pnb_home": {"corporate_tieups": ["psu", "SAIL", "govt", "defence"], "available_regions": ["pan_india"]},
    "bob_home": {"corporate_tieups": ["psu", "govt"], "available_regions": ["pan_india"]},
    "canara_home": {"corporate_tieups": ["psu", "govt"], "available_regions": ["pan_india"]},
    "federal_home": {"corporate_tieups": [], "available_regions": ["Kerala", "Karnataka", "Tamil Nadu", "Maharashtra", "Delhi", "Gujarat"]},
    "union_home": {"corporate_tieups": ["psu", "govt"], "available_regions": ["pan_india"]},
    "sbi_car": {"corporate_tieups": ["psu", "SAIL", "govt", "defence"], "available_regions": ["pan_india"]},
    "hdfc_car": {"corporate_tieups": ["gcc", "private", "TCS"], "available_regions": ["pan_india"]},
    "icici_car": {"corporate_tieups": ["gcc", "private"], "available_regions": ["pan_india"]},
    "axis_car": {"corporate_tieups": ["private"], "available_regions": ["pan_india"]},
    "tata_car": {"corporate_tieups": ["Tata Group", "private"], "available_regions": ["pan_india"]},
    "pnb_car": {"corporate_tieups": ["psu", "SAIL", "govt"], "available_regions": ["pan_india"]},
    "sbi_gold": {"corporate_tieups": [], "available_regions": ["pan_india"]},
    "hdfc_gold": {"corporate_tieups": [], "available_regions": ["pan_india"]},
    "muthoot_gold": {"corporate_tieups": [], "available_regions": ["Kerala", "Tamil Nadu", "Karnataka", "Andhra Pradesh", "Telangana", "Maharashtra", "Delhi", "Gujarat"]},
    "manappuram_gold": {"corporate_tieups": [], "available_regions": ["Kerala", "Tamil Nadu", "Karnataka", "Andhra Pradesh", "Telangana", "Maharashtra"]},
    "canara_gold": {"corporate_tieups": [], "available_regions": ["pan_india"]},
    "sbi_refinance": {"corporate_tieups": ["psu", "govt"], "available_regions": ["pan_india"]},
    "hdfc_refinance": {"corporate_tieups": ["gcc", "private"], "available_regions": ["pan_india"]},
    "icici_refinance": {"corporate_tieups": ["gcc", "private"], "available_regions": ["pan_india"]},
    "axis_refinance": {"corporate_tieups": ["private"], "available_regions": ["pan_india"]},
}
